# Vector Exceptions
class QdrantClientConnectionError(Exception):...
class VectorNotFoundError(Exception):...

# Domain specific 
class NoteFoundError(Exception):...
class UserAlreadyExistsError(Exception): ...
class IncorrectCredentials(Exception): ...